services:
    ReCaptcha\ReCaptcha:
        arguments:
            $secret: '%env(RECAPTCHA_SECRET_KEY)%'
            $requestMethod: '@ReCaptcha\RequestMethod'

    ReCaptcha\RequestMethod: '@ReCaptcha\RequestMethod\CurlPost'
    ReCaptcha\RequestMethod\CurlPost: null
