services:
    # Registramos la clase de Google como un servicio para que Symfony la reconozca
    ReCaptcha\ReCaptcha:
        arguments:
            $secret: '%env(RECAPTCHA_SECRET_KEY)%'
            $requestMethod: '@ReCaptcha\RequestMethod'

    # Configuramos el método de envío Curl
    ReCaptcha\RequestMethod: '@ReCaptcha\RequestMethod\CurlPost'
    ReCaptcha\RequestMethod\CurlPost: null
